import { TConfigApp } from '../types/config';


export const APP_CONFIG_DEFAULTS: TConfigApp = {
  assets: {
    browserConfig: false,
    favicon: { input: '' },
    framework: {
      eslintignore: false,
      prettierignore: false,
    },
    indexHtml: {
      metaCoverSocials: '',
      preLoader: false,
      tokensMeta: {
        appleMobileWebAppCapable: '',
        appleMobileWebAppStatusBarStyle: '',
        appleTouchFullscreen: '',
        applicationName: '',
        description: '',
        formatDetection: '',
        htmlLang: 'en-US',
        linkRelSearchTitle: '',
        mobileWebAppCapable: '',
        msapplicationNavbuttonColor: '',
        msapplicationStarturl: '',
        msapplicationTileColor: '',
        ogDescription: '',
        ogImageAlt: '',
        ogImageHeight: '',
        ogImageType: '',
        ogImageWidth: '',
        ogLocale: '',
        ogSiteName: '',
        ogTitle: '',
        ogType: '',
        ogUrl: '',
        owner: '',
        replyTo: '',
        robots: '',
        themeColor: '',
        title: '',
        twitterAppIdGoogleplay: '',
        twitterAppIdIpad: '',
        twitterAppIdIphone: '',
        twitterAppNameGoogleplay: '',
        twitterAppNameIpad: '',
        twitterAppNameIphone: '',
        twitterAppUrlGoogleplay: '',
        twitterAppUrlIpad: '',
        twitterAppUrlIphone: '',
        twitterCard: '',
        twitterCreator: '',
        twitterCreatorId: '',
        twitterDescription: '',
        twitterImage: '',
        twitterImageAlt: '',
        twitterPlayer: '',
        twitterPlayerHeight: '',
        twitterPlayerStream: '',
        twitterPlayerWidth: '',
        twitterSite: '',
        twitterSiteId: '',
        twitterTitle: '',
        urlRSSFeed: '',
        viewport: '',
      },
    },
    license: false,
    manifest: false,
    robots: false,
    searchXml: false,
  },
  outputDir: 'web-assets-generator',
  tokensMain: {
    appPlaceholderBackgroundColor: '',
    author: '',
    authorAccountTwitter: '',
    authorEmail: '',
    authorUrl: '',
    description: '',
    language: 'en-US',
    msapplicationTileColor: '',
    name: '',
    siteUrl: '',
    startUrl: '',
    themeColor: '',
    title: '',
  },
};
