name: CI
on: [push]
jobs:
  publish:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
          # Defaults to the user or organization that owns the workflow file
          scope: '@garvae'
      - run: yarn
      - run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

#jobs:
#  check:
#    name: Check on Node ${{ matrix.node }} and ${{ matrix.os }}
#    run: echo "TEST ACTION"
#
#    runs-on: ${{ matrix.os }}
#    strategy:
#      matrix:
#        node: ['18.x']
#        os: [ubuntu-latest, windows-latest, macOS-latest]
#
#    steps:
#      - name: Checkout repo
#        uses: actions/checkout@v3
#
#      - name: Use Node ${{ matrix.node }}
#        uses: actions/setup-node@v3
#        with:
#          node-version: ${{ matrix.node }}
#
#      - name: Install deps
#        uses: bahmutov/npm-install@v1
#
#      - name: Lint
#        run: yarn lint
#
#      - name: Test
#        run: yarn test
