name: Publish
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Publish manually'
        required: true
        default: 'warning'
        type: choice
        options:
          - info
          - warning
          - debug
      tags:
        description: 'Publish manually'
        required: false
        type: boolean
      environment:
        description: 'Publish manually'
        type: environment
        required: true

  workflow_run:
    workflows: [ "CI" ]
    branches: [ master ]
    types:
      - completed
jobs:
  publish:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
          # Defaults to the user or organization that owns the workflow file
          scope: '@garvae'
      - run: yarn
      - run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
